apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eswarmaganti/k8s-nginx.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: app
